<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title'];

    public function getRouteKeyName()
    {
        return 'slug';
    }


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($category) {
            $category->slug = Str::slug($category->title);
        });
    }


    public function questions(){
        return $this->hasMany(Question::class);
    }
}
